<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseAvalonia>true</UseAvalonia>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Proxima.Analytics\Proxima.Analytics.csproj" />
    <ProjectReference Include="..\Proxima.Application\Proxima.Application.csproj" />
    <ProjectReference Include="..\Proxima.Infrastructure\Proxima.Infrastructure.csproj" />
    <ProjectReference Include="..\Proxima.Importing\Proxima.Importing.csproj" />
    <ProjectReference Include="..\Proxima.Sync\Proxima.Sync.csproj" />
  </ItemGroup>
</Project>
