<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Proxima.Application\Proxima.Application.csproj" />
    <ProjectReference Include="..\Proxima.Domain\Proxima.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PdfSharp" Version="6.2.2" />
  </ItemGroup>
</Project>
