<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Proxima.Core\Proxima.Core.csproj" />
    <ProjectReference Include="..\..\src\Proxima.Infrastructure\Proxima.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Proxima.App\Proxima.App.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.4" />
  </ItemGroup>
</Project>
